/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated from shared/
 * Run 'npm run sync:shared' to update
 */

import { z } from "zod";

import { ACCOUNT_TYPES, type AccountType } from "../constants";

const accountTypeValues = Object.values(ACCOUNT_TYPES) as [
  AccountType,
  ...AccountType[],
];

export const accountSchema = z.object({
  _id: z.string().optional(),
  name: z.string().min(1, "Account name is required"),
  institution: z.string().optional(),
  amount: z.coerce
    .number()
    .min(0, "Amount must be positive")
    .refine(
      (val) => /^\d*\.?\d{0,2}$/.test(val.toString()),
      "Amount can have at most 2 decimal places"
    ),
  type: z.enum(accountTypeValues),
  acceptsFunds: z.boolean(),
  receivesSalary: z.boolean(),
  isDefault: z.boolean(),
  targetMonthlyAmount: z
    .object({
      amount: z.coerce
        .number()
        .min(0, "Target amount must be positive")
        .refine(
          (val) => /^\d*\.?\d{0,2}$/.test(val.toString()),
          "Target amount can have at most 2 decimal places"
        ),
      splitBetween: z.coerce
        .number()
        .min(1, "Split between must be at least 1 person")
        .max(10, "Split between cannot exceed 10 people"),
    })
    .optional()
    .nullable(),
});

// Output type (after transformation/coercion)
export type AccountInput = z.infer<typeof accountSchema>;
// Input type (before transformation - what forms send)
export type AccountFormInput = z.input<typeof accountSchema>;
