/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated from shared/
 * Run 'npm run sync:shared' to update
 */

import { z } from "zod";

export const savingsSchema = z.object({
  _id: z.string().optional(),
  name: z.string().min(1, "Please provide a savings name."),
  amount: z.coerce
    .number()
    .min(0, "Amount must be positive")
    .refine(
      (val) => /^\d*\.?\d{0,2}$/.test(val.toString()),
      "Amount can have at most 2 decimal places"
    ),
  account: z.string().min(1, "Please provide an account ID."),
  dueDate: z.coerce.number().int().min(1).max(31),
  dueDateType: z.enum(["1", "31", "custom"]).optional(),
});

// Output type (after transformation/coercion)
export type SavingsInput = z.infer<typeof savingsSchema>;
// Input type (before transformation - what forms send)
export type SavingsFormInput = z.input<typeof savingsSchema>;
